
package jp.yahooapis.ss.V5.BidLandscapeService;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BidLandscapeService", targetNamespace = "http://ss.yahooapis.jp/V5", wsdlLocation = "https://sandbox.ss.yahooapis.jp/services/V5.0/BidLandscapeService?wsdl")
public class BidLandscapeService
    extends Service
{

    private final static URL BIDLANDSCAPESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(jp.yahooapis.ss.V5.BidLandscapeService.BidLandscapeService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = jp.yahooapis.ss.V5.BidLandscapeService.BidLandscapeService.class.getResource(".");
            url = new URL(baseUrl, "https://sandbox.ss.yahooapis.jp/services/V5.0/BidLandscapeService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://sandbox.ss.yahooapis.jp/services/V5.0/BidLandscapeService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BIDLANDSCAPESERVICE_WSDL_LOCATION = url;
    }

    public BidLandscapeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BidLandscapeService() {
        super(BIDLANDSCAPESERVICE_WSDL_LOCATION, new QName("http://ss.yahooapis.jp/V5", "BidLandscapeService"));
    }

    /**
     * 
     * @return
     *     returns BidLandscapeServiceInterface
     */
    @WebEndpoint(name = "BidLandscapeService")
    public BidLandscapeServiceInterface getBidLandscapeService() {
        return super.getPort(new QName("http://ss.yahooapis.jp/V5", "BidLandscapeService"), BidLandscapeServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BidLandscapeServiceInterface
     */
    @WebEndpoint(name = "BidLandscapeService")
    public BidLandscapeServiceInterface getBidLandscapeService(WebServiceFeature... features) {
        return super.getPort(new QName("http://ss.yahooapis.jp/V5", "BidLandscapeService"), BidLandscapeServiceInterface.class, features);
    }

}
