
package jp.yahooapis.ss.V5.AdGroupCriterionService;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AdGroupCriterionService", targetNamespace = "http://ss.yahooapis.jp/V5", wsdlLocation = "https://sandbox.ss.yahooapis.jp/services/V5.0/AdGroupCriterionService?wsdl")
public class AdGroupCriterionService
    extends Service
{

    private final static URL ADGROUPCRITERIONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(jp.yahooapis.ss.V5.AdGroupCriterionService.AdGroupCriterionService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = jp.yahooapis.ss.V5.AdGroupCriterionService.AdGroupCriterionService.class.getResource(".");
            url = new URL(baseUrl, "https://sandbox.ss.yahooapis.jp/services/V5.0/AdGroupCriterionService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://sandbox.ss.yahooapis.jp/services/V5.0/AdGroupCriterionService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ADGROUPCRITERIONSERVICE_WSDL_LOCATION = url;
    }

    public AdGroupCriterionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdGroupCriterionService() {
        super(ADGROUPCRITERIONSERVICE_WSDL_LOCATION, new QName("http://ss.yahooapis.jp/V5", "AdGroupCriterionService"));
    }

    /**
     * 
     * @return
     *     returns AdGroupCriterionServiceInterface
     */
    @WebEndpoint(name = "AdGroupCriterionService")
    public AdGroupCriterionServiceInterface getAdGroupCriterionService() {
        return super.getPort(new QName("http://ss.yahooapis.jp/V5", "AdGroupCriterionService"), AdGroupCriterionServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdGroupCriterionServiceInterface
     */
    @WebEndpoint(name = "AdGroupCriterionService")
    public AdGroupCriterionServiceInterface getAdGroupCriterionService(WebServiceFeature... features) {
        return super.getPort(new QName("http://ss.yahooapis.jp/V5", "AdGroupCriterionService"), AdGroupCriterionServiceInterface.class, features);
    }

}
